Task 4 completed :)
original4sure/reporting-utils pull request #3
Opened 2023-09-20 11:30 UTC by Mugetsu42069

2023-09-22 02:28 UTC, jonscyr requested changes

2023-09-22 02:28 UTC, jonscyr commented on Bipintask4.py
> +
wrap these in functions. have a main function which calls other functions.

give a brief description on what this script is doing at the top of the file as a 2 or 3 line comment

2023-09-23 10:33 UTC, Mugetsu42069 commented on Bipintask4.py
> +
made the changes

2023-09-25 06:55 UTC, jonscyr requested changes

2023-09-25 06:55 UTC, jonscyr commented on Bipintask4.py
> +# This script reads JSON files containing schema information, generates JSON schemas
bad file name, follow shaurya's file structure.

2023-09-25 11:53 UTC, Mugetsu42069 commented on Bipintask4.py
> +# This script reads JSON files containing schema information, generates JSON schemas
done

2023-09-25 12:16 UTC, jonscyr approved these changes

2023-09-25 12:16 UTC, merged